export const INCR_ADULT = 'INCR_ADULT';
export const DECR_ADULT = 'DECR_ADULT';
export const INCR_CHILD = 'INCR_CHILD';
export const DECR_CHILD = 'DECR_CHILD';
export const TRAVEL_TYPE_SELECT = 'TRAVEL_TYPE_SELECT';
export const TRAVEL_CLASS_SELECT = 'TRAVEL_CLASS_SELECT';
export const SET_DEPARTURE_DATE = 'SET_DEPARTURE_DATE';
export const SET_RETURN_DATE = 'SET_RETURN_DATE';
export const SET_AIRPORT_LIST = 'SET_AIRPORT_LIST';
export const SHOW_AIRPORT_SEARCH = 'SHOW_AIRPORT_SEARCH'; 
export const SET_AIRPORT = 'SET_AIRPORT'; 
export const SET_FLIGHT_LIST = 'SET_FLIGHT_LIST'; 
export const SET_LOADING_VIEW = 'SET_LOADING_VIEW';
export const INCR_FLIGHT_LIST_PAGE = 'INCR_FLIGHT_LIST_PAGE';
export const DECR_FLIGHT_LIST_PAGE = 'DECR_FLIGHT_LIST_PAGE';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const SET_DEPARTURE_FILTER = 'SET_DEPARTURE_FILTER';
export const SET_ARRIVAL_FILTER = 'SET_ARRIVAL_FILTER';
export const SET_PRICE_FILTER = 'SET_PRICE_FILTER';





